language: objective-c
osx_image: xcode11
sudo: true

before_install:
  - rvm install 2.6.4
  - rvm use 2.6.4
  - brew update
  - gem install cocoapods --pre
  - pod --version
  - rm -rf ~/.cocoapods
  - pod setup
  - pod install --verbose --no-repo-update
  - gem install xcpretty


before_script:
  - export QINIU_TEST_ENV="travis"

script:
  - bash hack/network_loss.sh 0.5

after_success:
  - bash <(curl -s https://codecov.io/bash)
